name: Azure Function Twistcli Demo

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PRISMA_USER: ${{ secrets.PRISMA_USER }}
      PRISMA_PASSWORD: ${{ secrets.PRISMA_PASSWORD }}
    steps:

      - uses: actions/checkout@v4
      - name: Set up Python

        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies and zip file
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages

      - name: Zip the file
        run: zip -r myfunction.zip .

      - name: Download twistcli binary
        run: |
            curl -k \                                                                                                            1 ✘
            -H "Content-Type: application/json" \
            -X GET -o twistcli \
            -d \
            '{
                "username":"$PRISMA_USER",
                "password":"$PRISMA_PASSWORD"
            }' \
            https://app0.cloud.twistlock.com/panw-app0-310/api/v1/util/twistcli

      - name: Make Twistcli executable
        run: chmod +x twistcli

      - name: List files
        run: ls -lh

      - name: Perform twistcli scan
        run: twistcli serverless scan -u $PRISMA_USER -p $PRISMA_PASSWORD \
            --address https://app0.cloud.twistlock.com/panw-app0-310 myfunction.zip
